# Generated by Django 4.2.10 on 2024-08-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_unique_course_title_lesson'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_author_course_title'),
        ),
    ]
